server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/social
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: content
  sql:
    init:
      mode: never
springdoc:
  swagger-ui:
    path: /docs
jwt:
  secret: ${JWT_SECRET:5e657129b22a97783bf85796c089284ec0043a1918422ff2b10fb663b4794913}